<?xml version="1.0"?>
<package format="2">
  <name>gazebo_sim_worlds</name>
  <version>0.1.0</version>
  <description>Reusable Gazebo Classic world and model assets for the XGC2 simulation suite.</description>

  <maintainer email="lxk@example.com">lxk</maintainer>
  <license>BSD</license>

  <buildtool_depend>catkin</buildtool_depend>
  <exec_depend>gazebo_ros</exec_depend>
  <exec_depend>xgc2_gazebo_scene</exec_depend>
  <test_depend>python3-nose</test_depend>
  <test_depend>python3-yaml</test_depend>
  <export>
    <build_type>catkin</build_type>
    <gazebo_ros gazebo_model_path="${prefix}/models"/>
  </export>
</package>
